# Save as: %USERPROFILE%\.continue\config.yaml
# This config sets GPT-5 for chat, edits, apply, and autocomplete.
name: Local Assistant
version: 1.0.0
schema: v1

models:
  - name: gpt5-default
    provider: openai
    model: gpt-5
    apiKey: ${ secrets.OPENAI_API_KEY }
    roles: [chat, edit, apply]
    defaultCompletionOptions:
      temperature: 0.2
      maxTokens: 2000
    chatOptions:
      baseSystemMessage: |
        You are a repo-aware coding assistant. When asked to modify code:
        1) propose a short plan first,
        2) output minimal unified diffs with correct file paths relative to the repo root,
        3) update or add tests when behavior changes.
        Prefer diffs over prose. Never invent filenames or remove type-safety without explicit permission.

  - name: gpt5-autocomplete
    provider: openai
    model: gpt-5
    apiKey: ${ secrets.OPENAI_API_KEY }
    roles: [autocomplete]
    autocompleteOptions:
      onlyMyCode: true
      debounceDelay: 250
      maxPromptTokens: 1024

context:
  - provider: file
  - provider: code
  - provider: diff
  - provider: repo-map
    params:
      includeSignatures: false
  - provider: open
    params:
      onlyPinned: false
  - provider: terminal
  - provider: currentFile
  - provider: problems
  - provider: tree

# Rules in .continue/rules are auto-discovered.

prompts:
  - uses: file:///Users/Comp/debapp5/.continue/prompts/01-plan-diff-test.md
  - uses: file:///Users/Comp/debapp5/.continue/prompts/02-generate-tests.md
